logging.level.org.springframework:
  orm.jpa: INFO
  org.jpa.JpaTransactionManager: DEBUG
  transaction: INFO
  transaction.interceptor: TRACE

spring:
  application.name: ShareIt
  main.banner-mode: OFF
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC+3
        ddl-auto: none
        format_sql: true
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: "org.postgresql.Driver"
  sql.init.mode: always
